name: Architecture Document Check

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ feature/*, release/* ]

jobs:
  check-architecture-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check for architecture documents
        run: |
          # Get the feature or release name from the branch name
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "Checking branch: $BRANCH_NAME"
          
          # If it's a feature branch, extract feature name
          if [[ $BRANCH_NAME == feature/* ]]; then
            FEATURE_NAME=$(echo $BRANCH_NAME | sed 's/feature\///')
            echo "Feature name: $FEATURE_NAME"
            
            # Check if changes to architecture docs directory exist in this branch
            DOC_CHANGES=$(git diff --name-only origin/develop..HEAD | grep -E "^docs/architecture/")
            
            if [ -z "$DOC_CHANGES" ]; then
              echo "::error::No documentation changes found. Each feature must update or add architecture documentation."
              exit 1
            fi
            
            # Check if any diagrams are included
            MERMAID_CHANGES=$(git diff origin/develop..HEAD | grep -E "```mermaid")
            
            if [ -z "$MERMAID_CHANGES" ]; then
              echo "::warning::No Mermaid diagrams found in changes. Consider adding visual documentation."
            fi
            
            echo "Architecture documentation check passed."
          fi